### ISSUE TITLE
GitHub Navigation Issue

### ISSUE THREAD

**Issue by adanieljohnson** [WFU-TLC/flc_discussion_board#1]
This is definitely a novice GitHub user question, but we all start somewhere. Is there no simple way to create folders inside of GitHub? I can create folders in my local copy of a repo then push them, but seems like it would be handy to be able to do it directly inside the repo.

**Comment by francojc** [comment]
Technically you cannot create an empty folder/directory in GitHub --either pushing from your local repository or directly on the GitHub repository. To work around this limitation, you need to create a directory with a file named '.gitkeep' inside this directory. The prefixed '.' means the file is hidden from view on your OS and only serves as a placeholder to ensure the directory will be tracked by git/GitHub.

This issue is discussed on StackOverflow [here](https://stackoverflow.com/questions/12258399/how-to-create-folder-in-github-repository#12258453). The relevant instructions for creating the 'empty' directory are these: 

- go to the repository (and folder inside which you want to create another folder)
- click on New file
- on the text field for the file name, first write the folder name you want to create
- then add a final "/" which will create a folder and open a new field for a filename
- then create the file named '.gitkeep' (which is conventionally used to make git track otherwise empty folders, not a git feature though)
- finally click Commit new file (at the bottom of the page)

I hope this helps.

**Comment by adanieljohnson** [comment]
That's what I needed!
D

**Comment by francojc** [comment]
Great.
